version: 0.2

phases:
    install:
      runtime-versions:
        nodejs: 10
      commands:
      - echo "hello"
      - npm install -g @angular/cli
      - npm install --save-dev @angular-devkit/build-angular
      - echo "end install"
      - ng build
      - echo S3 bucket is cleared.
      - aws s3 cp dist s3://rpas.dev/RPAS --recursive
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
